"""added savings tables

Revision ID: 4348dfda7550
Revises: bae8f922ecc3
Create Date: 2023-08-18 04:07:35.071806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4348dfda7550"
down_revision = "bae8f922ecc3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "savings_goal",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("total_amount", sa.Float(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_savings_goal_id"), "savings_goal", ["id"], unique=False)
    op.create_table(
        "savings_entry",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("savings_goal_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["savings_goal_id"],
            ["savings_goal.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_savings_entry_id"), "savings_entry", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_savings_entry_id"), table_name="savings_entry")
    op.drop_table("savings_entry")
    op.drop_index(op.f("ix_savings_goal_id"), table_name="savings_goal")
    op.drop_table("savings_goal")
    # ### end Alembic commands ###
