"""added foriegn keys

Revision ID: bae8f922ecc3
Revises: f68f8ce223b2
Create Date: 2023-07-24 01:23:05.958243

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'bae8f922ecc3'
down_revision = 'f68f8ce223b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'budget', 'category', ['category_id'], ['id'])
    op.create_foreign_key(None, 'expense', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expense', type_='foreignkey')
    op.drop_constraint(None, 'budget', type_='foreignkey')
    # ### end Alembic commands ###
